attention_head_size: 1
categorical_groups: {}
causal_attention: true
dataset_parameters:
  add_encoder_length: true
  add_relative_time_idx: true
  add_target_scales: true
  allow_missing_timesteps: true
  categorical_encoders:
    __group_id__router_id: !!python/object:pytorch_forecasting.data.encoders.NaNLabelEncoder
      add_nan: false
      classes_:
        router_1: 0
        router_2: 1
        router_3: 2
      classes_vector_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - &id001 !!python/name:numpy.ndarray ''
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 3
        - !!python/object/apply:numpy.dtype
          args:
          - U8
          - false
          - true
          state: !!python/tuple
          - 3
          - <
          - null
          - null
          - null
          - 32
          - 4
          - 8
        - false
        - !!binary |
          cgAAAG8AAAB1AAAAdAAAAGUAAAByAAAAXwAAADEAAAByAAAAbwAAAHUAAAB0AAAAZQAAAHIAAABf
          AAAAMgAAAHIAAABvAAAAdQAAAHQAAABlAAAAcgAAAF8AAAAzAAAA
      warn: true
    application_type: !!python/object:pytorch_forecasting.data.encoders.NaNLabelEncoder
      add_nan: false
      classes_:
        web: 0
      classes_vector_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - !!python/object/apply:numpy.dtype
          args:
          - U3
          - false
          - true
          state: !!python/tuple
          - 3
          - <
          - null
          - null
          - null
          - 12
          - 4
          - 8
        - false
        - !!binary |
          dwAAAGUAAABiAAAA
      warn: true
    location: !!python/object:pytorch_forecasting.data.encoders.NaNLabelEncoder
      add_nan: false
      classes_:
        datacenter_1: 0
        datacenter_2: 1
        datacenter_3: 2
      classes_vector_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 3
        - !!python/object/apply:numpy.dtype
          args:
          - U12
          - false
          - true
          state: !!python/tuple
          - 3
          - <
          - null
          - null
          - null
          - 48
          - 4
          - 8
        - false
        - !!binary |
          ZAAAAGEAAAB0AAAAYQAAAGMAAABlAAAAbgAAAHQAAABlAAAAcgAAAF8AAAAxAAAAZAAAAGEAAAB0
          AAAAYQAAAGMAAABlAAAAbgAAAHQAAABlAAAAcgAAAF8AAAAyAAAAZAAAAGEAAAB0AAAAYQAAAGMA
          AABlAAAAbgAAAHQAAABlAAAAcgAAAF8AAAAzAAAA
      warn: true
    router_id: !!python/object:pytorch_forecasting.data.encoders.NaNLabelEncoder
      add_nan: false
      classes_:
        router_1: 0
        router_2: 1
        router_3: 2
      classes_vector_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 3
        - !!python/object/apply:numpy.dtype
          args:
          - U8
          - false
          - true
          state: !!python/tuple
          - 3
          - <
          - null
          - null
          - null
          - 32
          - 4
          - 8
        - false
        - !!binary |
          cgAAAG8AAAB1AAAAdAAAAGUAAAByAAAAXwAAADEAAAByAAAAbwAAAHUAAAB0AAAAZQAAAHIAAABf
          AAAAMgAAAHIAAABvAAAAdQAAAHQAAABlAAAAcgAAAF8AAAAzAAAA
      warn: true
  constant_fill_strategy: null
  group_ids:
  - router_id
  lags: null
  max_encoder_length: 60
  max_prediction_length: 7
  min_encoder_length: 20
  min_prediction_idx: !!python/object/apply:numpy.core.multiarray.scalar
  - &id002 !!python/object/apply:numpy.dtype
    args:
    - i8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    AAAAAAAAAAA=
  min_prediction_length: 1
  predict_mode: false
  randomize_length: null
  scalers:
    bandwidth_mbps_normalized_center: !!python/object:sklearn.preprocessing._data.StandardScaler
      _sklearn_version: 1.7.1
      copy: true
      feature_names_in_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - &id004 !!python/object/apply:numpy.dtype
          args:
          - O8
          - false
          - true
          state: !!python/tuple
          - 3
          - '|'
          - null
          - null
          - null
          - -1
          - -1
          - 63
        - false
        - - bandwidth_mbps_normalized_center
      mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - &id003 !!python/object/apply:numpy.dtype
          args:
          - f8
          - false
          - true
          state: !!python/tuple
          - 3
          - <
          - null
          - null
          - null
          - -1
          - -1
          - 0
        - false
        - !!binary |
          e4IAFg162L8=
      n_features_in_: 1
      n_samples_seen_: !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        uAsAAAAAAAA=
      scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          tO31HsQkyj8=
      var_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          /kZH8OhbpT8=
      with_mean: true
      with_std: true
    bandwidth_mbps_normalized_scale: !!python/object:sklearn.preprocessing._data.StandardScaler
      _sklearn_version: 1.7.1
      copy: true
      feature_names_in_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id004
        - false
        - - bandwidth_mbps_normalized_scale
      mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          q7grhhnG4j8=
      n_features_in_: 1
      n_samples_seen_: !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        uAsAAAAAAAA=
      scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          pzTJ69oe4D8=
      var_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          kQI6WPE90D8=
      with_mean: true
      with_std: true
    day_of_week: !!python/object:sklearn.preprocessing._data.StandardScaler
      _sklearn_version: 1.7.1
      copy: true
      feature_names_in_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id004
        - false
        - - day_of_week
      mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          y6FFtvP9B0A=
      n_features_in_: 1
      n_samples_seen_: !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        uAsAAAAAAAA=
      scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          fgjjAokBAEA=
      var_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          za57KxIDEEA=
      with_mean: true
      with_std: true
    encoder_length: !!python/object:sklearn.preprocessing._data.StandardScaler
      _sklearn_version: 1.7.1
      copy: true
      feature_names_in_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id004
        - false
        - - encoder_length
      mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          AAAAAAAAAAA=
      n_features_in_: 1
      n_samples_seen_: !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        uAsAAAAAAAA=
      scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          AAAAAAAA8D8=
      var_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          AAAAAAAAAAA=
      with_mean: true
      with_std: true
    hour: !!python/object:sklearn.preprocessing._data.StandardScaler
      _sklearn_version: 1.7.1
      copy: true
      feature_names_in_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id004
        - false
        - - hour
      mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          AAAAAAAAMEA=
      n_features_in_: 1
      n_samples_seen_: !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        uAsAAAAAAAA=
      scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          AAAAAAAA8D8=
      var_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          AAAAAAAAAAA=
      with_mean: true
      with_std: true
    relative_time_idx: !!python/object:sklearn.preprocessing._data.StandardScaler
      _sklearn_version: 1.7.1
      copy: true
      feature_names_in_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id004
        - false
        - - relative_time_idx
      mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          AAAAAAAAAAA=
      n_features_in_: 1
      n_samples_seen_: !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        uAsAAAAAAAA=
      scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          AAAAAAAA8D8=
      var_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          AAAAAAAAAAA=
      with_mean: true
      with_std: true
  static_categoricals:
  - router_id
  - location
  - application_type
  static_reals: null
  target: bandwidth_mbps_normalized
  target_normalizer: &id006 !!python/object:pytorch_forecasting.data.encoders.GroupNormalizer
    _groups:
    - router_id
    _method_kwargs: {}
    center: true
    groups:
    - router_id
    method: standard
    method_kwargs: {}
    missing_:
      center: -0.31425249373780284
      scale: 0.40812859293706144
    norm_: !!python/object:pandas.core.frame.DataFrame
      _flags:
        allows_duplicate_labels: true
      _metadata: []
      _mgr: !!python/object/apply:pandas.core.internals.managers.BlockManager
      - !!python/tuple
        - !!python/object/apply:pandas._libs.internals._unpickle_block
          - !!python/object/apply:numpy.core.multiarray._reconstruct
            args:
            - *id001
            - !!python/tuple
              - 0
            - !!binary |
              Yg==
            state: !!python/tuple
            - 1
            - !!python/tuple
              - 2
              - 3
            - *id003
            - false
            - !!binary |
              aJTSfbYc1L9PmyeqPjTGv66SjbeoG+W/C4rOY8ce2j90vqiTYiO0P5VmE0c+X/Q/
          - !!python/object/apply:builtins.slice
            - 0
            - 2
            - 1
          - 2
      - - !!python/object/apply:pandas.core.indexes.base._new_Index
          - &id005 !!python/name:pandas.core.indexes.base.Index ''
          - data: !!python/object/apply:numpy.core.multiarray._reconstruct
              args:
              - *id001
              - !!python/tuple
                - 0
              - !!binary |
                Yg==
              state: !!python/tuple
              - 1
              - !!python/tuple
                - 2
              - *id004
              - false
              - - center
                - scale
            name: null
        - !!python/object/apply:pandas.core.indexes.base._new_Index
          - *id005
          - data: !!python/object/apply:numpy.core.multiarray._reconstruct
              args:
              - *id001
              - !!python/tuple
                - 0
              - !!binary |
                Yg==
              state: !!python/tuple
              - 1
              - !!python/tuple
                - 3
              - *id002
              - false
              - !!binary |
                AAAAAAAAAAABAAAAAAAAAAIAAAAAAAAA
            name: router_id
      _typ: dataframe
      attrs: {}
    scale_by_group: false
    transformation: softplus
  time_idx: index
  time_varying_known_categoricals: null
  time_varying_known_reals:
  - hour
  - day_of_week
  time_varying_unknown_categoricals: null
  time_varying_unknown_reals:
  - bandwidth_mbps_normalized
  variable_groups: null
  weight: null
dropout: 0.1
embedding_labels:
  application_type:
    web: 0
  location:
    datacenter_1: 0
    datacenter_2: 1
    datacenter_3: 2
  router_id:
    router_1: 0
    router_2: 1
    router_3: 2
embedding_paddings: []
embedding_sizes:
  application_type: !!python/tuple
  - 1
  - 1
  location: !!python/tuple
  - 3
  - 3
  router_id: !!python/tuple
  - 3
  - 3
hidden_continuous_size: 8
hidden_continuous_sizes: {}
hidden_size: 16
learning_rate: 0.03
log_gradient_flow: false
log_interval: -1
log_val_interval: -1
lstm_layers: 1
mask_bias: -1000000000.0
max_encoder_length: 60
monotone_constaints: {}
monotone_constraints: {}
optimizer: adam
optimizer_params: null
output_size: 1
output_transformer: *id006
reduce_on_plateau_min_lr: 1.0e-05
reduce_on_plateau_patience: 1000
reduce_on_plateau_reduction: 2.0
share_single_variable_networks: false
static_categoricals:
- router_id
- location
- application_type
static_reals:
- encoder_length
- bandwidth_mbps_normalized_center
- bandwidth_mbps_normalized_scale
time_varying_categoricals_decoder: []
time_varying_categoricals_encoder: []
time_varying_reals_decoder:
- hour
- day_of_week
- relative_time_idx
time_varying_reals_encoder:
- hour
- day_of_week
- relative_time_idx
- bandwidth_mbps_normalized
weight_decay: 0.0
x_categoricals:
- router_id
- location
- application_type
x_reals:
- encoder_length
- bandwidth_mbps_normalized_center
- bandwidth_mbps_normalized_scale
- hour
- day_of_week
- relative_time_idx
- bandwidth_mbps_normalized
